[package]
name = "simple_kv_store"
version = "0.1.0"
edition = "2021"

[dependencies]
simple_kv_store = { path = "./datastore" }
crossterm = "0.26"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
